markdown: kramdown
baseurl: ""
exclude: ['README.md, JEKYLL.md']
permalink: pretty
timezone: Kolkata/Asia
sass:
    sass_dir: assets/css
    style: compressed
plugins:
    - jekyll-minifier
    - jekyll-last-modified-at
